### ISSUE TITLE
csv gem doesn't exist

### ISSUE THREAD

**Issue by drallgood** [MartinThoma/jekyll-caption-tag#1]
When I try to install the required gems, it tells me, that the csv gem couldn't be found:

> ERROR:  Could not find a valid gem 'csv' (>= 0) in any repository

**Comment by MartinThoma** [comment]
Oh, I'm sorry, `csv` seems not to be a gem. It seems to be always installed with ruby.

I've updated the README. Just install it without `csv`. Does it work?

**Comment by drallgood** [comment]
It does kind of. I'll open a new issue for that one :) Thanks!
