### ISSUE TITLE
context.registers[:page] is Nil

### ISSUE THREAD

**Issue by drallgood** [MartinThoma/jekyll-caption-tag#2]
When I try to generate the site, I get the following error:

> Liquid Exception: undefined method `[]' for nil:NilClass in file.md

This happens due to the fact that `context.registers[:page]` evaluates to nil (line 103).

**Comment by drallgood** [comment]
Oh. I should probably mention, that I'm using Octopress. So, this issue might be specific to that app.

**Comment by drallgood** [comment]
ok got it. Octopress uses an oooooold version of Jekyll (0.12), which doesn't include the patch needed for this to work.

**Comment by MartinThoma** [comment]
Ok. Do you think you can get it work?

By the way, I've added an automatically generated documentation: https://rawgithub.com/MartinThoma/jekyll-caption-tag/master/doc/Jekyll/CaptionTag.html

However, I'm not sure if it is useful.

**Comment by drallgood** [comment]
Hmm... I'm considering the options right now. I either have to move from octopress to plain jekyll or somehow fix this error. Really considering the former right now.

**Comment by drallgood** [comment]
After updating to octopuses 3.0 this plugin is working. I had to change a few things, though. 

Is there a reason why the plugin creates a new thumbnail every time you rebuild the site?

**Comment by drallgood** [comment]
I'm still seeing some weird behavior. For example this:

> [Warning] /Users/patrice/git/casualkitchen/source/&ldquo;/uploads/2014-03-09-hackfleisch-kraut-pfanne/2G3A7793-1024x682.jpg&rdquo; 

Looks like the plugin is (for some reason) called twice. Once with the correct caption tag data and the second time with escaped values. 
Any idea why?

**Comment by MartinThoma** [comment]
Nice to hear that it works with Octopress 3.0 :-)

The reason why the thumbnail is created every time is that I remove the "captions" folder every time (automatically, with another script) before my plugin runs. Hmm ... perhaps I should write a log-file so that the plugin can know which captions it had created before (and does not need to create again). Do you think that would be a good idea?

I don't know why the plugin is called twice.

**Comment by drallgood** [comment]
Yeah I think that might be a good idea. This whole image processing stuff takes a lot of time (once the number of images starts growing).

I've got another issue: The thumbnails are created in the source folder, not in the destination folder. As a result, new files aren't published immediately. At least they aren't for me. Is that intentional?

**Comment by MartinThoma** [comment]
> The thumbnails are created in the source folder, not in the destination folder. As a result, new files aren't published immediately. At least they aren't for me. Is that intentional?

There was some problem with directly creating them in the `_site` folder. (I don't remember which one it was :-/ - I am currently at my parents, making holidays for a few days. I will hopefully find time to try that in the next week.)

I've added this to my TODO list (Readme.md).
