### ISSUE TITLE
Doesn't work in RSS feeds if the caption contains a link (or double quote)

### ISSUE THREAD

**Issue by drallgood** [MartinThoma/jekyll-caption-tag#3]
I've got a page, where the caption text includes a link.
`{% caption align="alignleft" width="512" caption="
Source: [www.icondrawer.com](http://www.icondrawer.com)" 
url="uploads/1350492413_cake.png" alt="Cake" height="512" class="size-full wp-image-983" %}`

When generating a category RSS feed for that page (using https://github.com/recurser/jekyll-plugins), that link is rendered to HTML first before applying the caption tag, which results in quotes being present inside the caption attribute:
`align="alignleft" width="512" caption="
Source: <a href="http://www.icondrawer.com">www.icondrawer.com</a>" 
url="uploads/1350492413_cake.png" alt="Cake" height="512" class="size-full wp-image-983"`

Which subsequently results in:

>   Liquid Exception: Unclosed quoted field on line 5. in categories/allgemein/atom.xml
> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/csv.rb:1867:in `block in shift': Unclosed quoted field on line 5. (CSV::MalformedCSVError)

So far I haven't been able to solve this issue. Any suggestions?

(The same thing happens, if your caption text contains a double quote, but that's easy enough to prevent)

**Comment by MartinThoma** [comment]
I suggest to insert links directly (as HTML) and using `'` instead of `"`. I know it's inconvenient, but I can't think of a simple fix for this problem.

If I wanted to accept this input, I would have to adjust the way I parse the content of the caption tag in such a way that I try to find `<a href=...</a>` before I parse it.

(By the way, I've just pushed version 1.5 of this plugin.)

**Comment by drallgood** [comment]
Yep. That's what I did. 

Turns out, the issue was in part caused by the other plugin which rendered the pages before it was supposed to do so.
Now, markdown content inside the caption attribute isn't rendered at all. Which is fine for now :)

**Comment by MartinThoma** [comment]
Great :-) Please keep giving me feedback. I want to provide a good caption plugin and your feedback helps me to do so.
