### ISSUE TITLE
Issues with the image URL and permalink structure

### ISSUE THREAD

**Issue by drallgood** [MartinThoma/jekyll-caption-tag#4]
Is there a reason, why the plugin is using the _posts folder as the base path for the urls and not the source folder?

When I'm using an url like `url="/uploads/2014-03-25-test/2G3A8950.jpg"` in my posts, 
the plugin can't find the image because it's located in the source folder (source/uploads/..) instead of the posts folder.

Additionally, changing the url to `url="../uploads/2014-03-25-test/2G3A8950.jpg"` (like you did in your examples) does work, but due to the fact that it uses a relative url it won't work with a permalink structure like `/:year/:month/:day/:title/`

**Comment by MartinThoma** [comment]
(my commit message was wrong - it was not about this issue)

Currently, the plugin takes the path of the post (that means the one of the markdown file which is not necessarily in `_posts` e.g. [my author page](https://github.com/MartinThoma/MartinThoma.github.io/tree/source/author/martin-thoma)) as base for its relative path.

1 ) I guess I could do both: Take the markdown file as base and, if the plugin does not find the image, take the root project folder as base. 

2) Probably my plugin should replace all relative URLs with absolute URLs. But I'm not sure what would be a good way to do so. I could parse the attribute `permalink` in the sites config if and only if the currently parsed file is in `_posts` and use `baseurl`. But I'm not sure how `permalink` is parsed.

**Comment by drallgood** [comment]
Is there even a use-case for using a relative url?
I don't think anybody (in his right mind) would put the images in the posts folder, so they will always reside somewhere in the source folder. Thus you would use "absolute" urls anyway (absolute to the source folder).

In that case, they would be absolute to the url_root too

**Comment by MartinThoma** [comment]
> Is there even a use-case for using a relative url?
> I don't think anybody (in his right mind) would put the images in the posts folder, so they will always reside somewhere in the source folder.

Although I don't put images in `_posts`, I think some people might do that.

I've added the check in [line 139](https://github.com/MartinThoma/jekyll-caption-tag/blob/master/caption_tag.rb#L139). This is not directly a solution to the issues with permalink structure, but if you see relative urls as being relative to the projects root folder it is no problem any longer.

**Comment by drallgood** [comment]
Seems to work :)

Thanks!
