### ISSUE TITLE
Caption URL is missing if caption isn't generated

### ISSUE THREAD

**Issue by drallgood** [MartinThoma/jekyll-caption-tag#8]
We introduced an issue with 67e51d2222a3065d91ff45985da71577ee58c4cb:
When no caption image is generated (e.g. because Scaled width = original width) the caption_url variable is never set. As a result, the image won't be shown in these cases.

**Comment by MartinThoma** [comment]
I'm sorry, I simply forgot pushing the fix 06584016602f61470946247c310cea4635893c48.

**Comment by drallgood** [comment]
That was quick! Thanks.
